# Goal
# print(goal.ur_goto_pose_goal_scan_type_integer)
# print(goal.ur_goto_pose_goal_timeout_integer)
# print(goal.ur_goto_pose_system_side_string)
# print(goal.ur_goto_pose_position)
# print(goal.ur_goto_pose_orientation)
#int32 ur_goto_pose_goal_zone_integer
#int32 ur_goto_pose_goal_item_integer
# string ur_goto_pose_pendant_file_name
#geometry_msgs/Pose ur_goto_pose_goal_Pose

int32 ur_goto_pose_scan_type_integer
int32 ur_goto_pose_timeout_integer
string ur_goto_pose_system_side_string
float32[3] ur_goto_pose_position
float32[4] ur_goto_pose_orientation


---
# Result
string ur_goto_pose_result_string

---
# Feedback string ur_goto_pose_feedback_string
int32 ur_goto_pose_feedback_percent_int
int32 ur_goto_pose_feedback_action_server_code_int
# string ur_goto_pose_feedback_teach_pendant_string
#float32[9] ur_goto_pose_feedback_triple_XYZ_float_array
#geometry_msgs/Pose ur_goto_pose_feedback_Pose
#geometry_msgs/Quaternion ur_goto_pose_feedback_Quaternion
