# Goal
# print(goal.ur_stow_goal_scan_type_integer)
# print(goal.ur_stow_goal_timeout_integer)
# print(goal.ur_stow_system_side_string)
# print(goal.ur_stow_pendant_file_name)
#
int32 ur_stow_goal_timeout_integer
#int32 ur_stow_goal_zone_integer
int32 ur_stow_goal_scan_type_integer
#int32 ur_stow_goal_item_integer
string ur_stow_system_side_string
string ur_stow_pendant_file_name
#float32[9] ur_stow_goal_triple_XYZ_float_array
#geometry_msgs/Pose ur_stow_goal_Pose
#geometry_msgs/Quaternion ur_stow_goal_Quaternion


---
# Result
string ur_stow_result_string

---
# Feedback string ur_stow_feedback_string
int32 ur_stow_feedback_percent_int
int32 ur_stow_feedback_action_server_code_int
string ur_stow_feedback_teach_pendant_string
#float32[9] ur_stow_feedback_triple_XYZ_float_array
#geometry_msgs/Pose ur_stow_feedback_Pose
#geometry_msgs/Quaternion ur_stow_feedback_Quaternion
